ABausG/home_widget

- ios/Classes/SwiftHomeWidgetPlugin.swift
Hi,
This is a fix for the error: "cannot find 'WidgetCenter' in scope"
It happens when building the app for iOS
This error will not happen on iOS Simulator neither when building to a connected device since it will detect the OS arch and because of that will build correctly.
But when building the IPA for any device. The error will happen. So with this fix we avoid that.
Regards,
> Fixes cannot find 'WidgetCenter' in scope error

- android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetPlugin.kt
Hi,
this fixes the casting issue that occurs when trying to register background callback to register clicks on parts of a home widget.
Best regards,
Aljosa
> Fix failure to register background callback

- ios/Classes/SwiftHomeWidgetPlugin.swift
Hello!
Open URL method should return false if the link isn't meant for this plugin, so another plugin can take care of it.
Thank you!
> Fix: avoid collisions with open url methods from other plugins

- android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetIntent.kt
Make the plugin work for Android 12
> Make PendingIntents immutable for Android 12.

- .github/workflows/main.yml
- CHANGELOG.md
- README.md
- example/integration_test/ios_test.dart
- ios/Classes/SwiftHomeWidgetPlugin.swift
- pubspec.yaml
Adding a no-op operation on iOS for `registerBackgroundCallback`
> #39 MissingPluginException(No implementation found for method registerBackgroundCallback)

- README.md
Hello! I have noticed that putting xml files in `android/app/res/layout` and `android/app/res/xml` doesn't work and gradle can't find them. After some research I've found this stackoverflow post about the same error: https://stackoverflow.com/questions/69917184/flutter-androidmanifest-cannot-find-xml-resource
This pull request fixes this, by adding working paths for the platform setup section documentation.
> Change xml paths in README.md

- CHANGELOG.md
- README.md
- android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetPlugin.kt
- lib/home_widget.dart
- pubspec.yaml
- test/home_widget_test.dart
This solves issues created by variants with different applicationIds
> Allow specification of fully qualified class name for android

- README.md
- example/ios/Podfile
- ios/home_widget.podspec
- lib/home_widget_callback_dispatcher.dart
As discussed in https://github.com/flutter/flutter/issues/109248
An official document explaining why that vm:entry-point thing is necessary: https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
This Fixes ABausG/home_widget#96 
Since the app crashes on release mode in flutter 3.3+ and it is not a breaking change, I suggest releasing a new version ASAP
> Add vm-entry to callbackDispatcher

- README.md
The path of creating a widget in Xcode might have been changed since writing the original `README`. This is just a small fix for the path to be accurate.
You need to go throw `File > [New] > Target > Widget Extension` to create a widget.
> Fix xcode creating Widget path

- example/lib/main.dart
The example is wrong. You get following error if you try to update the widget from the background on Android release mode.
```
E/flutter ( 9318): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter ( 9318): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
E/flutter ( 9318): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter ( 9318): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.
```
I've added a @pragma("vm:entry-point") annotation in the example to the callbackDispatcher() function. This change fixes the error.
Can you already say when version 2.0 will be available on pub.dev?
> annotate callbackDispatcher with @pragma("vm:entry-point")

- ios/Classes/HomeWidgetBackgroundWorker.swift
I noticed a problem with the execution of the `HomeWidgetBackgroundWorker`. The first tap on my widget's button wouldn't execute the Dart callback the first time it had been called (with the app being terminated). I believe the if condition in `run` should be the other way around:
- if the setup is completed and the `FlutterEngine` is started we can send the event directly to the `MethodChannel`.
- if the setup is not yet completed we should add the event to the queue and when the background is initialized (`HomeWidget.backgroundInitialized` is received) the queue will be emptied and the event send to the existing method channel.
I'm also not sure if we need to get the dispatcher here and log it, but I leave it for you to decide.
> fix: First event being missed in iOS background worker

- README.md
Link to the rendered README https://github.com/ueman/home_widget/blob/7f255317b5f69bdd880708de12e0cdf32897e5a4/README.md
This uses the `<kbd>` HTML tag to render menu paths a bit nicer, see 
I've also fixed and added syntax highlighting to a broken code fence.
> docs: Improve README Formatting

- ios/Classes/HomeWidgetBackgroundWorker.swift
On iOS, the `HomeWidgetBackgroundWorker` doesn't function because the `isSetupCompleted` flag is always false. This happens because `isSetupCompleted` is set to `true` only when the `backgroundInitialized` callback runs after the first event is added to the queue, which happens rarely. To fix it, simply move `isSetupCompleted` outside the `while` loop.
> fix: HomeWidgetBackgroundWorker on iOS not setting Setup as completed

- android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetIntent.kt
Launching an app on Android 14+ requires an additional option to be passed to `PendingIntent`. More information can be found here: https://developer.android.com/guide/components/activities/background-starts
> fix: Android 14+ launch support

- example/integration_test/ios_test.dart
- ios/Classes/SwiftHomeWidgetPlugin.swift
Thanks for this awesome package.
This PR adds support for Uint8List, Int32List, Int64List, Float64List. The StandardMessageCodec encodes them to FlutterStandardTypedData in Swift. Passing this type of data to UserDefaults.SetValue results in a runtime crash.
I added a special case to extract the data and cast it to the built-in type `Data`. With this small change saving the data to UserDefaults completes successfully.
> feat: support Uint8List as FlutterStandardTypedData on iOS

- example/ios/Flutter/AppFrameworkInfo.plist
- example/ios/Podfile
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Classes/SwiftHomeWidgetPlugin.swift
I'm proposing a simple fix to avoid errors caused by `NS_EXTENSION_UNAVAILABLE_IOS` when adding `home_widget` to the widget target. This fix uses `performSelector` to bypass the `NS_EXTENSION_UNAVAILABLE_IOS` macro. It might not be ideal, but it works and is very simple.
> fix: addApplicationDelegate unavailable in iOS

- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetPlugin.kt
- example/integration_test/android_test.dart
- example/integration_test/ios_test.dart
- example/lib/main.dart
- ios/Classes/SwiftHomeWidgetPlugin.swift
- lib/home_widget.dart
- lib/home_widget_info.dart
- test/home_widget_info_test.dart
- test/home_widget_test.dart
Would address 
https://github.com/ABausG/home_widget/issues/129
https://github.com/ABausG/home_widget/issues/223
https://github.com/ABausG/home_widget/issues/37
> feat: Add a way to to obtain information about the pinned widgets

- ios/Classes/HomeWidgetBackgroundWorker.swift
There is an issue with how `HomeWidgetBackgroundWorker` uses `async/await` in its iOS implementation. Currently, the `run` method returns immediately, before the platform channel can be initialized and the Flutter callback performed.
I've refactored the `HomeWidgetBackgroundWorker` with a proper `async/await` implementation. Now, the `run` method will return only after the interactivity callback in Flutter has been executed.
> Fix: iOS background worker

- packages/home_widget/android/src/main/kotlin/es/antonborri/home_widget/HomeWidgetIntent.kt
This PR fixes a runtime error in HomeWidgetLaunchIntent when attempting to start a background activity on Android 15. Due to new system restrictions (as documented [here](https://developer.android.com/guide/components/activities/background-starts?hl=en#creator-pendingintent)), the configuration of pendingIntentBackgroundActivityStartMode needs to be handled differently depending on the Android version.
Closes #303 #328
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/abausg/home_widget/blob/main/CHANGELOG.md
> fix: Runtime error when starting background activity on Android 15

- .github/cspell.yaml
- .github/workflows/main.yml
- .gitignore
- docs/index.mdx
- packages/home_widget/README.md
- packages/home_widget/android/build.gradle
- packages/home_widget/example/android/app/build.gradle
- packages/home_widget/example/android/gradle.properties
- packages/home_widget/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/home_widget/example/android/settings.gradle
- packages/home_widget/example/pubspec.yaml
- packages/home_widget/pubspec.yaml
- packages/home_widget/test/background_test.dart
Fix build and badges
[Conventional Commit]: https://conventionalcommits.org
[CHANGELOG]: https://github.com/abausg/home_widget/blob/main/CHANGELOG.md
> chore: Fix build and update gradle
